### ISSUE TITLE
spatial extent incorrectly displayed 

### ISSUE THREAD

**Issue by valentinedwv** [CINERGI/cinergi-annotator#2]
Ilya to send Burak extent computaitons on Thu

**Comment by izaslavsky** [comment]
Burak, very roughly zoom level can be, for your 500x380 canvas

Zoom = 1
If lat_extent < 72 and lon_extent < 130 then zoom = 2, else
If lat_extent < 36 and lon_extent < 650 then zoom = 3, else
If lat_extent < 18 and lon_extent < 32.5 then zoom = 4, else
If lat_extent < 9 and lon_extent < 16.25 then zoom = 5, else
If lat_extent < 4.5 and lon_extent < 8.125 then zoom = 6, else
If lat_extent < 2.25 and lon_extent < 4.0625 then zoom = 7, else
If lat_extent < 1.125 and lon_extent < 2 then zoom = 8

I am sure it can be written more elegantly.
that would produce a bounding box frame that leaves ample margin, and has enough context outside the box

**Comment by bozyurt** [comment]
Zoom calc logic is added to cinergi-annotator and it is available at
http://132.249.238.151:8080/cinergi-annotator/
